version: "1.0"
name: biokb_wcvp

services:
  api:
    build: .
    container_name: biokb_wcvp
    environment:
      CONNECTION_STR: "mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}"
      NEO4J_URI: "bolt://${NEO4J_HOST}:${NEO4J_PORT_BOLT}"
    ports:
      - ${API_PORT}:8000
    volumes:
      - ~/.biokb/wcvp:/root/.biokb/wcvp

networks:
  default:
    name: biokb_network
    external: true