[project]
name = "wcvp"
version = "0.1.0"
description = "Manage and query World Checklist of Vascular Plants data"
authors = [
    {name = "MARIA MARTINEZ", email = "s0mamart@uni-bonn.com"},
    {name = "Xiaoxuan Yu", email = "s04xyu@uni-bonn.de"},
    {name = "Samana Fatima", email = "S22sfati@uni-bonn.de"},
]
dependencies = ["sqlalchemy>=2.0.39", "pandas>=2.2.3", "pymysql>=1.1.1", "cryptography>=44.0.2"]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = true


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[dependency-groups]
dev = [
    "podman-compose>=1.3.0",
]
tests = [
    "pytest>=8.3.5",
]
